# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(verbose_name='\u0422\u0435\u043a\u0441\u0442'),
        ),
    ]
