# Generated by Django 3.2.5 on 2022-01-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('idim', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Идентификатор')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Название')),
                ('img', models.FileField(upload_to='photo/', verbose_name='Фотография')),
                ('comment', models.TextField(verbose_name='Содержание')),
                ('datead', models.DateField(auto_now_add=True, verbose_name='Дата загрузки')),
            ],
            options={
                'verbose_name': 'Фотографии',
                'verbose_name_plural': 'Фотографии',
            },
        ),
    ]
