# Generated by Django 3.2.5 on 2022-01-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20220128_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='img',
            field=models.FileField(upload_to='photo/', verbose_name='Фотография'),
        ),
    ]
