# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('idmn', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='\u0418\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('content', models.TextField(verbose_name='\u0421\u043e\u0434\u0435\u0440\u0436\u0430\u043d\u0438\u0435')),
                ('datead', models.DateField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0437\u0430\u0433\u0440\u0443\u0437\u043a\u0438')),
            ],
            options={
                'verbose_name': '\u0413\u043b\u0430\u0432\u043d\u0430\u044f',
                'verbose_name_plural': '\u0413\u043b\u0430\u0432\u043d\u0430\u044f',
            },
        ),
    ]
