# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Writings',
            fields=[
                ('idwr', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='\u0418\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('genre', models.CharField(max_length=20, verbose_name='\u0416\u0430\u043d\u0440')),
                ('datewr', models.DateField(verbose_name='\u0414\u0430\u0442\u0430 \u043d\u0430\u043f\u0438\u0441\u0430\u043d\u0438\u044f')),
                ('datead', models.DateField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0437\u0430\u0433\u0440\u0443\u0437\u043a\u0438')),
                ('content', models.TextField(verbose_name='\u0422\u0435\u043a\u0441\u0442')),
                ('description', models.TextField(verbose_name='\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439')),
            ],
            options={
                'verbose_name': '\u041f\u0440\u043e\u0438\u0437\u0432\u0435\u0434\u0435\u043d\u0438\u0435',
                'verbose_name_plural': '\u041f\u0440\u043e\u0438\u0437\u0432\u0435\u0434\u0435\u043d\u0438\u044f',
            },
        ),
    ]
